version: '2'
services:
    skynet-app:
        image: skynet
        external_links:
            - skynet-postgresql:postgresql
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/skynet
        ports:
            - 8080:8080
    skynet-postgresql:
        extends:
            file: postgresql.yml
            service: skynet-postgresql
